import type { Role } from "./types/role";
import type { StaffUser } from "./types/user";

export const staffUserSeed: StaffUser[] = [
  {
    id: "usr-001",
    firstName: "Sonia",
    lastName: "Khelifi",
    email: "sonia.khelifi@solidcare.tn",
    phone: "+216 71 245 100",
    role: "admin",
    status: "active",
    lastActiveAt: "2026-09-06",
  },
  {
    id: "usr-002",
    firstName: "Karim",
    lastName: "Jaziri",
    email: "karim.jaziri@solidcare.tn",
    phone: "+216 71 245 101",
    role: "doctor",
    status: "active",
    lastActiveAt: "2026-09-05",
  },
  {
    id: "usr-003",
    firstName: "Mariem",
    lastName: "Cherif",
    email: "mariem.cherif@solidcare.tn",
    phone: "+216 71 245 102",
    role: "receptionist",
    status: "active",
    lastActiveAt: "2026-09-06",
  },
  {
    id: "usr-004",
    firstName: "Hatem",
    lastName: "Gharbi",
    email: "hatem.gharbi@solidcare.tn",
    phone: "+216 71 245 103",
    role: "doctor",
    status: "invited",
    lastActiveAt: "",
  },
  {
    id: "usr-005",
    firstName: "Leila",
    lastName: "Mansouri",
    email: "leila.mansouri@solidcare.tn",
    phone: "+216 71 245 104",
    role: "receptionist",
    status: "suspended",
    lastActiveAt: "2026-07-21",
  },
];

export const roleSeed: Role[] = [
  {
    id: "rol-admin",
    key: "admin",
    name: "Administrator",
    description: "Full access to clinic data, staff accounts and settings.",
    permissions: [
      "patients.read",
      "patients.create",
      "patients.update",
      "patients.delete",
      "appointments.read",
      "appointments.create",
      "appointments.update",
      "appointments.delete",
      "consultations.read",
      "consultations.create",
      "consultations.update",
      "prescriptions.read",
      "prescriptions.create",
      "payments.read",
      "payments.create",
      "administration.manage",
    ],
    usersCount: 1,
  },
  {
    id: "rol-doctor",
    key: "doctor",
    name: "Doctor",
    description: "Manages consultations, prescriptions and their own schedule.",
    permissions: [
      "patients.read",
      "patients.update",
      "appointments.read",
      "appointments.update",
      "consultations.read",
      "consultations.create",
      "consultations.update",
      "prescriptions.read",
      "prescriptions.create",
      "payments.read",
    ],
    usersCount: 2,
  },
  {
    id: "rol-receptionist",
    key: "receptionist",
    name: "Receptionist",
    description: "Handles the front desk: patients, appointments and payments.",
    permissions: [
      "patients.read",
      "patients.create",
      "patients.update",
      "appointments.read",
      "appointments.create",
      "appointments.update",
      "appointments.delete",
      "payments.read",
      "payments.create",
    ],
    usersCount: 2,
  },
];
