import type { Role, Permission } from "./types/role";
import type { StaffUser } from "./types/user";

export const staffUserSeed: StaffUser[] = [
  {
    id: "usr-001",
    firstName: "Sonia",
    lastName: "Khelifi",
    email: "sonia.khelifi@solidcare.tn",
    phone: "+216 71 245 100",
    role: "admin",
    status: "active",
    lastActiveAt: "2026-09-06",
  },
  {
    id: "usr-002",
    firstName: "Karim",
    lastName: "Jaziri",
    email: "karim.jaziri@solidcare.tn",
    phone: "+216 71 245 101",
    role: "doctor",
    departmentId: "dep-001",
    status: "active",
    lastActiveAt: "2026-09-05",
  },
  {
    id: "usr-003",
    firstName: "Mariem",
    lastName: "Cherif",
    email: "mariem.cherif@solidcare.tn",
    phone: "+216 71 245 102",
    role: "receptionist",
    status: "active",
    lastActiveAt: "2026-09-06",
  },
  {
    id: "usr-004",
    firstName: "Hatem",
    lastName: "Gharbi",
    email: "hatem.gharbi@solidcare.tn",
    phone: "+216 71 245 103",
    role: "department_head",
    departmentId: "dep-001",
    status: "active",
    lastActiveAt: "2026-09-04",
  },
  {
    id: "usr-005",
    firstName: "Leila",
    lastName: "Mansouri",
    email: "leila.mansouri@solidcare.tn",
    phone: "+216 71 245 104",
    role: "team_leader",
    departmentId: "dep-002",
    status: "active",
    lastActiveAt: "2026-09-05",
  },
  {
    id: "usr-006",
    firstName: "Amel",
    lastName: "Trabelsi",
    email: "amel.trabelsi@solidcare.tn",
    phone: "+216 71 245 107",
    role: "nurse",
    departmentId: "dep-005",
    status: "active",
    lastActiveAt: "2026-09-06",
  },
  {
    id: "usr-007",
    firstName: "Nizar",
    lastName: "Bouzid",
    email: "nizar.bouzid@solidcare.tn",
    phone: "+216 71 245 105",
    role: "doctor",
    departmentId: "dep-003",
    status: "invited",
    lastActiveAt: "",
  },
];

const allPermissions: Permission[] = [
  "patients.read",
  "patients.create",
  "patients.update",
  "patients.delete",
  "appointments.read",
  "appointments.create",
  "appointments.update",
  "appointments.delete",
  "consultations.read",
  "consultations.create",
  "consultations.update",
  "prescriptions.read",
  "prescriptions.create",
  "examinations.read",
  "examinations.create",
  "examinations.update",
  "hospitalizations.read",
  "hospitalizations.create",
  "hospitalizations.update",
  "payments.read",
  "payments.create",
  "departments.read",
  "departments.manage",
  "rooms.read",
  "rooms.manage",
  "wards.read",
  "wards.manage",
  "operating_rooms.read",
  "operating_rooms.manage",
  "equipment.read",
  "equipment.manage",
  "maintenance.read",
  "maintenance.manage",
  "planning.read",
  "planning.manage",
  "staff.read",
  "staff.manage",
  "administration.manage",
  "audit.read",
];

export const roleSeed: Role[] = [
  {
    id: "rol-admin",
    key: "admin",
    name: "Administrateur",
    description: "Accès complet : clinique, ressources, personnel et paramètres.",
    permissions: allPermissions,
    usersCount: 1,
  },
  {
    id: "rol-department-head",
    key: "department_head",
    name: "Chef de département",
    description: "Pilote son département : équipes, salles, lits et interventions.",
    permissions: [
      "patients.read",
      "appointments.read",
      "appointments.create",
      "appointments.update",
      "consultations.read",
      "prescriptions.read",
      "examinations.read",
      "hospitalizations.read",
      "hospitalizations.create",
      "hospitalizations.update",
      "payments.read",
      "departments.read",
      "departments.manage",
      "rooms.read",
      "rooms.manage",
      "wards.read",
      "wards.manage",
      "operating_rooms.read",
      "operating_rooms.manage",
      "equipment.read",
      "equipment.manage",
      "maintenance.read",
      "maintenance.manage",
      "planning.read",
      "planning.manage",
      "staff.read",
    ],
    usersCount: 1,
  },
  {
    id: "rol-team-leader",
    key: "team_leader",
    name: "Chef d'équipe",
    description: "Coordonne médecins et planning de l'équipe.",
    permissions: [
      "patients.read",
      "appointments.read",
      "appointments.update",
      "consultations.read",
      "examinations.read",
      "hospitalizations.read",
      "departments.read",
      "rooms.read",
      "wards.read",
      "operating_rooms.read",
      "equipment.read",
      "planning.read",
      "staff.read",
    ],
    usersCount: 1,
  },
  {
    id: "rol-doctor",
    key: "doctor",
    name: "Médecin",
    description: "Espace médecin : consultations, ordonnances, examens, hospitalisations.",
    permissions: [
      "patients.read",
      "patients.update",
      "appointments.read",
      "appointments.update",
      "consultations.read",
      "consultations.create",
      "consultations.update",
      "prescriptions.read",
      "prescriptions.create",
      "examinations.read",
      "examinations.create",
      "hospitalizations.read",
      "hospitalizations.create",
      "payments.read",
      "departments.read",
      "rooms.read",
      "wards.read",
      "operating_rooms.read",
      "equipment.read",
      "planning.read",
    ],
    usersCount: 2,
  },
  {
    id: "rol-nurse",
    key: "nurse",
    name: "Infirmier / Infirmière",
    description: "Shift, patients hospitalisés, constantes et soins.",
    permissions: [
      "patients.read",
      "patients.update",
      "appointments.read",
      "hospitalizations.read",
      "hospitalizations.update",
      "wards.read",
      "rooms.read",
      "planning.read",
      "equipment.read",
    ],
    usersCount: 1,
  },
  {
    id: "rol-receptionist",
    key: "receptionist",
    name: "Réceptionniste",
    description: "Accueil, rendez-vous, admissions et disponibilités.",
    permissions: [
      "patients.read",
      "patients.create",
      "patients.update",
      "appointments.read",
      "appointments.create",
      "appointments.update",
      "appointments.delete",
      "hospitalizations.read",
      "hospitalizations.create",
      "payments.read",
      "payments.create",
      "wards.read",
      "rooms.read",
      "planning.read",
    ],
    usersCount: 1,
  },
];
