import type { Bed, WardRoom } from "./types";

/** Chambres d'hospitalisation — clinique tunisienne fictive. */
export const wardRoomSeed: WardRoom[] = [
  {
    id: "ward-001",
    code: "CH-201",
    floor: "2",
    departmentId: "dep-001",
    roomType: "double",
    bedCount: 2,
    status: "partial",
    notes: "Vue jardin — monitoring cardiaque",
    createdAt: "2025-02-10",
  },
  {
    id: "ward-002",
    code: "CH-202",
    floor: "2",
    departmentId: "dep-001",
    roomType: "single",
    bedCount: 1,
    status: "occupied",
    notes: "Chambre individuelle post-cathétérisme",
    createdAt: "2025-02-10",
  },
  {
    id: "ward-003",
    code: "CH-101",
    floor: "1",
    departmentId: "dep-002",
    roomType: "double",
    bedCount: 2,
    status: "available",
    notes: "Pédiatrie — lit parent accompagnant",
    createdAt: "2025-02-12",
  },
  {
    id: "ward-004",
    code: "CH-102",
    floor: "1",
    departmentId: "dep-002",
    roomType: "suite",
    bedCount: 2,
    status: "occupied",
    notes: "Suite famille",
    createdAt: "2025-02-12",
  },
  {
    id: "ward-005",
    code: "CH-301",
    floor: "3",
    departmentId: "dep-003",
    roomType: "double",
    bedCount: 2,
    status: "partial",
    notes: "Post-opératoire chirurgie générale",
    createdAt: "2025-03-01",
  },
  {
    id: "ward-006",
    code: "USI-01",
    floor: "3",
    departmentId: "dep-004",
    roomType: "icu",
    bedCount: 4,
    status: "partial",
    notes: "Unité de soins intensifs",
    createdAt: "2025-03-05",
  },
  {
    id: "ward-007",
    code: "CH-110",
    floor: "1",
    departmentId: "dep-005",
    roomType: "single",
    bedCount: 1,
    status: "maintenance",
    notes: "Climatisation hors service",
    createdAt: "2025-03-08",
  },
  {
    id: "ward-008",
    code: "CH-205",
    floor: "2",
    departmentId: "dep-006",
    roomType: "suite",
    bedCount: 1,
    status: "available",
    notes: "Gynécologie — suite maternité",
    createdAt: "2025-03-20",
  },
];

export const bedSeed: Bed[] = [
  {
    id: "bed-001",
    code: "CH-201-A",
    wardRoomId: "ward-001",
    status: "occupied",
    patientId: "pat-001",
    notes: "",
  },
  {
    id: "bed-002",
    code: "CH-201-B",
    wardRoomId: "ward-001",
    status: "available",
    notes: "",
  },
  {
    id: "bed-003",
    code: "CH-202-A",
    wardRoomId: "ward-002",
    status: "occupied",
    patientId: "pat-003",
    notes: "Surveillance rythmique",
  },
  {
    id: "bed-004",
    code: "CH-101-A",
    wardRoomId: "ward-003",
    status: "available",
    notes: "",
  },
  {
    id: "bed-005",
    code: "CH-101-B",
    wardRoomId: "ward-003",
    status: "cleaning",
    notes: "Nettoyage après sortie",
  },
  {
    id: "bed-006",
    code: "CH-102-A",
    wardRoomId: "ward-004",
    status: "occupied",
    patientId: "pat-004",
    notes: "",
  },
  {
    id: "bed-007",
    code: "CH-102-B",
    wardRoomId: "ward-004",
    status: "reserved",
    patientId: "pat-002",
    notes: "Admission prévue demain",
  },
  {
    id: "bed-008",
    code: "CH-301-A",
    wardRoomId: "ward-005",
    status: "occupied",
    patientId: "pat-005",
    notes: "J+2 post-op",
  },
  {
    id: "bed-009",
    code: "CH-301-B",
    wardRoomId: "ward-005",
    status: "available",
    notes: "",
  },
  {
    id: "bed-010",
    code: "USI-01-1",
    wardRoomId: "ward-006",
    status: "occupied",
    patientId: "pat-006",
    notes: "Ventilation non invasive",
  },
  {
    id: "bed-011",
    code: "USI-01-2",
    wardRoomId: "ward-006",
    status: "available",
    notes: "",
  },
  {
    id: "bed-012",
    code: "USI-01-3",
    wardRoomId: "ward-006",
    status: "maintenance",
    notes: "Moniteur en calibration",
  },
  {
    id: "bed-013",
    code: "USI-01-4",
    wardRoomId: "ward-006",
    status: "available",
    notes: "",
  },
  {
    id: "bed-014",
    code: "CH-110-A",
    wardRoomId: "ward-007",
    status: "maintenance",
    notes: "Chambre fermée",
  },
  {
    id: "bed-015",
    code: "CH-205-A",
    wardRoomId: "ward-008",
    status: "available",
    notes: "",
  },
];
