import type { Consultation } from "./types";

/** Fictional demo records only — never real patient data. */
export const consultationSeed: Consultation[] = [
  {
    id: "cns-001",
    patientId: "pat-001",
    doctorId: "doc-001",
    appointmentId: "apt-001",
    date: "2026-08-24",
    symptoms: "Persistent headache and fatigue for one week.",
    diagnosis: "Tension headache",
    treatment: "Rest, hydration, paracetamol 1g if needed.",
    temperature: 37.1,
    bloodPressure: "125/80",
    weight: 82,
    followUpDate: "2026-09-14",
    status: "finalised",
  },
  {
    id: "cns-002",
    patientId: "pat-002",
    doctorId: "doc-002",
    appointmentId: "apt-002",
    date: "2026-08-27",
    symptoms: "Chest tightness after exercise.",
    diagnosis: "Mild exercise-induced asthma",
    treatment: "Inhaler before physical activity.",
    temperature: 36.8,
    bloodPressure: "118/76",
    weight: 61,
    followUpDate: "2026-10-05",
    status: "finalised",
  },
  {
    id: "cns-003",
    patientId: "pat-003",
    doctorId: "doc-003",
    appointmentId: "apt-003",
    date: "2026-09-01",
    symptoms: "Itchy rash on both forearms.",
    diagnosis: "Contact dermatitis",
    treatment: "Topical corticosteroid for 7 days.",
    temperature: 36.6,
    bloodPressure: "120/78",
    weight: 74,
    followUpDate: "",
    status: "finalised",
  },
  {
    id: "cns-004",
    patientId: "pat-004",
    doctorId: "doc-001",
    appointmentId: "apt-004",
    date: "2026-09-03",
    symptoms: "Sore throat, low fever.",
    diagnosis: "Viral pharyngitis",
    treatment: "Symptomatic treatment, review in 5 days if no improvement.",
    temperature: 38.2,
    bloodPressure: "115/72",
    weight: 68,
    followUpDate: "2026-09-08",
    status: "draft",
  },
  {
    id: "cns-005",
    patientId: "pat-005",
    doctorId: "doc-004",
    appointmentId: "apt-005",
    date: "2026-09-04",
    symptoms: "Routine paediatric check-up.",
    diagnosis: "Healthy growth curve",
    treatment: "No treatment required.",
    temperature: 36.9,
    bloodPressure: "100/65",
    weight: 24,
    followUpDate: "2027-03-04",
    status: "finalised",
  },
  {
    id: "cns-006",
    patientId: "pat-006",
    doctorId: "doc-005",
    appointmentId: "apt-006",
    date: "2026-09-05",
    symptoms: "Knee pain after a fall.",
    diagnosis: "Mild ligament strain",
    treatment: "Rest, ice, physiotherapy referral.",
    temperature: 36.7,
    bloodPressure: "128/82",
    weight: 90,
    followUpDate: "2026-09-19",
    status: "draft",
  },
];
