import type { Patient } from "./types";

/** Fictional demo records only — never real patient data. */
export const patientSeed: Patient[] = [
  {
    id: "pat-001",
    reference: "P-2026-001",
    firstName: "Amine",
    lastName: "Ben Salah",
    gender: "male",
    dateOfBirth: "1988-04-12",
    phone: "+216 20 145 782",
    email: "amine.bensalah@example.tn",
    city: "Tunis",
    address: "12 rue de Marseille",
    bloodGroup: "O+",
    insurance: "CNAM",
    allergies: "Penicillin",
    notes: "Prefers morning appointments.",
    status: "active",
    createdAt: "2026-01-14",
  },
  {
    id: "pat-002",
    reference: "P-2026-002",
    firstName: "Ines",
    lastName: "Trabelsi",
    gender: "female",
    dateOfBirth: "1995-09-30",
    phone: "+216 55 903 214",
    email: "ines.trabelsi@example.tn",
    city: "Ariana",
    address: "5 avenue Habib Bourguiba",
    bloodGroup: "A+",
    insurance: "Assurances Maghrebia",
    allergies: "",
    notes: "",
    status: "active",
    createdAt: "2026-02-02",
  },
  {
    id: "pat-003",
    reference: "P-2026-003",
    firstName: "Mohamed",
    lastName: "Gharbi",
    gender: "male",
    dateOfBirth: "1972-01-08",
    phone: "+216 98 447 120",
    email: "m.gharbi@example.tn",
    city: "Sousse",
    address: "31 rue Ibn Khaldoun",
    bloodGroup: "B+",
    insurance: "CNAM",
    allergies: "Aspirin",
    notes: "Hypertension follow-up every 3 months.",
    status: "active",
    createdAt: "2026-02-19",
  },
  {
    id: "pat-004",
    reference: "P-2026-004",
    firstName: "Sarra",
    lastName: "Khelifi",
    gender: "female",
    dateOfBirth: "2001-06-21",
    phone: "+216 22 671 908",
    email: "sarra.khelifi@example.tn",
    city: "Sfax",
    address: "8 rue Farhat Hached",
    bloodGroup: "AB-",
    insurance: "",
    allergies: "Latex",
    notes: "",
    status: "active",
    createdAt: "2026-03-04",
  },
  {
    id: "pat-005",
    reference: "P-2026-005",
    firstName: "Youssef",
    lastName: "Mansouri",
    gender: "male",
    dateOfBirth: "1960-11-02",
    phone: "+216 71 332 004",
    email: "youssef.mansouri@example.tn",
    city: "Bizerte",
    address: "44 avenue de la Republique",
    bloodGroup: "O-",
    insurance: "CNAM",
    allergies: "",
    notes: "Diabetic, needs quarterly labs.",
    status: "active",
    createdAt: "2026-03-22",
  },
  {
    id: "pat-006",
    reference: "P-2026-006",
    firstName: "Nour",
    lastName: "Hamdi",
    gender: "female",
    dateOfBirth: "1993-02-17",
    phone: "+216 27 118 445",
    email: "nour.hamdi@example.tn",
    city: "Nabeul",
    address: "17 rue Taieb Mhiri",
    bloodGroup: "A-",
    insurance: "STAR Assurances",
    allergies: "",
    notes: "",
    status: "active",
    createdAt: "2026-04-08",
  },
  {
    id: "pat-007",
    reference: "P-2026-007",
    firstName: "Karim",
    lastName: "Jaziri",
    gender: "male",
    dateOfBirth: "1985-08-25",
    phone: "+216 52 774 601",
    email: "karim.jaziri@example.tn",
    city: "Monastir",
    address: "3 rue de l'Hopital",
    bloodGroup: "B-",
    insurance: "CNAM",
    allergies: "Iodine",
    notes: "",
    status: "archived",
    createdAt: "2025-11-30",
  },
  {
    id: "pat-008",
    reference: "P-2026-008",
    firstName: "Fatma",
    lastName: "Belhadj",
    gender: "female",
    dateOfBirth: "1978-05-14",
    phone: "+216 24 559 730",
    email: "fatma.belhadj@example.tn",
    city: "Tunis",
    address: "22 rue Alain Savary",
    bloodGroup: "AB+",
    insurance: "CNAM",
    allergies: "",
    notes: "Post-surgery monitoring.",
    status: "active",
    createdAt: "2026-04-27",
  },
  {
    id: "pat-009",
    reference: "P-2026-009",
    firstName: "Hedi",
    lastName: "Zouari",
    gender: "male",
    dateOfBirth: "1999-12-09",
    phone: "+216 29 640 187",
    email: "hedi.zouari@example.tn",
    city: "Gabes",
    address: "9 avenue Mohamed V",
    bloodGroup: "O+",
    insurance: "",
    allergies: "",
    notes: "",
    status: "active",
    createdAt: "2026-05-11",
  },
  {
    id: "pat-010",
    reference: "P-2026-010",
    firstName: "Leila",
    lastName: "Chaabane",
    gender: "female",
    dateOfBirth: "1966-03-28",
    phone: "+216 21 205 963",
    email: "leila.chaabane@example.tn",
    city: "Kairouan",
    address: "6 rue des Oliviers",
    bloodGroup: "A+",
    insurance: "CNAM",
    allergies: "Sulfa drugs",
    notes: "",
    status: "active",
    createdAt: "2026-06-01",
  },
  {
    id: "pat-011",
    reference: "P-2026-011",
    firstName: "Bilel",
    lastName: "Ferchichi",
    gender: "male",
    dateOfBirth: "1991-07-19",
    phone: "+216 26 883 471",
    email: "bilel.ferchichi@example.tn",
    city: "Tunis",
    address: "58 rue de Rome",
    bloodGroup: "B+",
    insurance: "Comar",
    allergies: "",
    notes: "",
    status: "active",
    createdAt: "2026-06-20",
  },
  {
    id: "pat-012",
    reference: "P-2026-012",
    firstName: "Rania",
    lastName: "Ayari",
    gender: "female",
    dateOfBirth: "2010-10-05",
    phone: "+216 23 410 556",
    email: "rania.ayari@example.tn",
    city: "Ben Arous",
    address: "14 rue Ali Belhouane",
    bloodGroup: "O+",
    insurance: "CNAM",
    allergies: "Pollen",
    notes: "Paediatric asthma follow-up.",
    status: "active",
    createdAt: "2026-07-09",
  },
];
