import type { Patient } from "./types";

/** Fictional demo records only — never real patient data. */
export const patientSeed: Patient[] = [
  {
    id: "pat-001",
    reference: "P-2026-001",
    firstName: "Amine",
    lastName: "Ben Salah",
    gender: "male",
    dateOfBirth: "1988-04-12",
    phone: "+216 20 145 782",
    email: "amine.bensalah@example.tn",
    city: "Tunis",
    address: "12 rue de Marseille",
    emergencyContactName: "Sami Ben Salah",
    emergencyContactPhone: "+216 20 145 783",
    bloodGroup: "O+",
    insurance: "CNAM",
    allergies: "Pénicilline",
    chronicConditions: "",
    medicalHistory: "Appendicectomie (2015). Vaccinations à jour.",
    notes: "Préfère les rendez-vous du matin.",
    status: "active",
    createdAt: "2026-01-14",
    updatedAt: "2026-09-01",
  },
  {
    id: "pat-002",
    reference: "P-2026-002",
    firstName: "Ines",
    lastName: "Trabelsi",
    gender: "female",
    dateOfBirth: "1995-09-30",
    phone: "+216 55 903 214",
    email: "ines.trabelsi@example.tn",
    city: "Ariana",
    address: "5 avenue Habib Bourguiba",
    emergencyContactName: "Rania Trabelsi",
    emergencyContactPhone: "+216 55 903 215",
    bloodGroup: "A+",
    insurance: "Assurances Maghrebia",
    allergies: "",
    chronicConditions: "",
    medicalHistory: "",
    notes: "",
    status: "active",
    createdAt: "2026-02-02",
    updatedAt: "2026-08-12",
  },
  {
    id: "pat-003",
    reference: "P-2026-003",
    firstName: "Mohamed",
    lastName: "Gharbi",
    gender: "male",
    dateOfBirth: "1972-01-08",
    phone: "+216 98 447 120",
    email: "m.gharbi@example.tn",
    city: "Sousse",
    address: "31 rue Ibn Khaldoun",
    emergencyContactName: "Fatma Gharbi",
    emergencyContactPhone: "+216 98 447 121",
    bloodGroup: "B+",
    insurance: "CNAM",
    allergies: "Aspirine",
    chronicConditions: "Hypertension artérielle",
    medicalHistory: "Suivi HTA depuis 2018. Échocardiographie annuelle.",
    notes: "Contrôle tensionnel tous les 3 mois.",
    status: "active",
    createdAt: "2026-02-19",
    updatedAt: "2026-09-05",
  },
  {
    id: "pat-004",
    reference: "P-2026-004",
    firstName: "Sarra",
    lastName: "Khelifi",
    gender: "female",
    dateOfBirth: "2001-06-21",
    phone: "+216 22 671 908",
    email: "sarra.khelifi@example.tn",
    city: "Sfax",
    address: "8 rue Farhat Hached",
    emergencyContactName: "Omar Khelifi",
    emergencyContactPhone: "+216 22 671 900",
    bloodGroup: "AB-",
    insurance: "",
    allergies: "Latex",
    chronicConditions: "",
    medicalHistory: "",
    notes: "",
    status: "active",
    createdAt: "2026-03-04",
    updatedAt: "2026-07-20",
  },
  {
    id: "pat-005",
    reference: "P-2026-005",
    firstName: "Youssef",
    lastName: "Mansouri",
    gender: "male",
    dateOfBirth: "1960-11-02",
    phone: "+216 71 332 004",
    email: "youssef.mansouri@example.tn",
    city: "Bizerte",
    address: "44 avenue de la République",
    emergencyContactName: "Nadia Mansouri",
    emergencyContactPhone: "+216 71 332 005",
    bloodGroup: "O-",
    insurance: "CNAM",
    allergies: "",
    chronicConditions: "Diabète de type 2",
    medicalHistory: "Diabète diagnostiqué en 2012. Bilan HbA1c trimestriel.",
    notes: "Besoin de bilans biologiques trimestriels.",
    status: "active",
    createdAt: "2026-03-22",
    updatedAt: "2026-09-02",
  },
  {
    id: "pat-006",
    reference: "P-2026-006",
    firstName: "Nour",
    lastName: "Hamdi",
    gender: "female",
    dateOfBirth: "1993-02-17",
    phone: "+216 27 118 445",
    email: "nour.hamdi@example.tn",
    city: "Nabeul",
    address: "17 rue Taieb Mhiri",
    emergencyContactName: "Anis Hamdi",
    emergencyContactPhone: "+216 27 118 446",
    bloodGroup: "A-",
    insurance: "STAR Assurances",
    allergies: "",
    chronicConditions: "",
    medicalHistory: "",
    notes: "",
    status: "active",
    createdAt: "2026-04-08",
    updatedAt: "2026-06-15",
  },
  {
    id: "pat-007",
    reference: "P-2026-007",
    firstName: "Karim",
    lastName: "Jaziri",
    gender: "male",
    dateOfBirth: "1985-08-25",
    phone: "+216 52 774 601",
    email: "karim.jaziri@example.tn",
    city: "Monastir",
    address: "3 rue de l'Hôpital",
    emergencyContactName: "Sonia Jaziri",
    emergencyContactPhone: "+216 52 774 602",
    bloodGroup: "B-",
    insurance: "CNAM",
    allergies: "Iode",
    chronicConditions: "",
    medicalHistory: "Dossier archivé à la demande du patient.",
    notes: "",
    status: "archived",
    createdAt: "2025-11-30",
    updatedAt: "2026-01-10",
  },
  {
    id: "pat-008",
    reference: "P-2026-008",
    firstName: "Fatma",
    lastName: "Belhadj",
    gender: "female",
    dateOfBirth: "1978-05-14",
    phone: "+216 24 559 730",
    email: "fatma.belhadj@example.tn",
    city: "Tunis",
    address: "22 rue Alain Savary",
    emergencyContactName: "Mehdi Belhadj",
    emergencyContactPhone: "+216 24 559 731",
    bloodGroup: "AB+",
    insurance: "CNAM",
    allergies: "",
    chronicConditions: "",
    medicalHistory: "Chirurgie orthopédique (2025). Suivi post-opératoire.",
    notes: "Surveillance post-chirurgie.",
    status: "active",
    createdAt: "2026-04-27",
    updatedAt: "2026-08-30",
  },
  {
    id: "pat-009",
    reference: "P-2026-009",
    firstName: "Hedi",
    lastName: "Zouari",
    gender: "male",
    dateOfBirth: "1999-12-09",
    phone: "+216 29 640 187",
    email: "hedi.zouari@example.tn",
    city: "Gabès",
    address: "9 avenue Mohamed V",
    emergencyContactName: "Aymen Zouari",
    emergencyContactPhone: "+216 29 640 188",
    bloodGroup: "O+",
    insurance: "",
    allergies: "",
    chronicConditions: "",
    medicalHistory: "",
    notes: "",
    status: "active",
    createdAt: "2026-05-11",
    updatedAt: "2026-05-11",
  },
  {
    id: "pat-010",
    reference: "P-2026-010",
    firstName: "Leila",
    lastName: "Chaabane",
    gender: "female",
    dateOfBirth: "1966-03-28",
    phone: "+216 21 205 963",
    email: "leila.chaabane@example.tn",
    city: "Kairouan",
    address: "6 rue des Oliviers",
    emergencyContactName: "Tarek Chaabane",
    emergencyContactPhone: "+216 21 205 964",
    bloodGroup: "A+",
    insurance: "CNAM",
    allergies: "Sulfamides",
    chronicConditions: "Asthme léger",
    medicalHistory: "Crises d'asthme saisonnières. Traitement de fond.",
    notes: "",
    status: "active",
    createdAt: "2026-06-01",
    updatedAt: "2026-08-18",
  },
  {
    id: "pat-011",
    reference: "P-2026-011",
    firstName: "Bilel",
    lastName: "Ferchichi",
    gender: "male",
    dateOfBirth: "1991-07-19",
    phone: "+216 26 883 471",
    email: "bilel.ferchichi@example.tn",
    city: "Tunis",
    address: "58 rue de Rome",
    emergencyContactName: "Imen Ferchichi",
    emergencyContactPhone: "+216 26 883 472",
    bloodGroup: "B+",
    insurance: "Comar",
    allergies: "",
    chronicConditions: "",
    medicalHistory: "",
    notes: "",
    status: "active",
    createdAt: "2026-06-20",
    updatedAt: "2026-06-20",
  },
  {
    id: "pat-012",
    reference: "P-2026-012",
    firstName: "Rania",
    lastName: "Ayari",
    gender: "female",
    dateOfBirth: "2010-10-05",
    phone: "+216 23 410 556",
    email: "rania.ayari@example.tn",
    city: "Ben Arous",
    address: "14 rue Ali Belhouane",
    emergencyContactName: "Salma Ayari",
    emergencyContactPhone: "+216 23 410 550",
    bloodGroup: "O+",
    insurance: "CNAM",
    allergies: "Pollen",
    chronicConditions: "Asthme pédiatrique",
    medicalHistory: "Suivi pédiatrique asthme depuis 2018.",
    notes: "Accompagnée par le parent.",
    status: "active",
    createdAt: "2026-07-09",
    updatedAt: "2026-09-03",
  },
];
