import type { StaffMember } from "./types";

export const staffSeed: StaffMember[] = [
  {
    id: "stf-001",
    firstName: "Amira",
    lastName: "Trabelsi",
    email: "a.trabelsi@solidcare.tn",
    phone: "+216 71 900 201",
    role: "nurse",
    departmentId: "dep-001",
    status: "active",
    shiftPreference: "morning",
    createdAt: "2025-11-12",
  },
  {
    id: "stf-002",
    firstName: "Youssef",
    lastName: "Guediche",
    email: "y.guediche@solidcare.tn",
    phone: "+216 71 900 202",
    role: "nurse",
    departmentId: "dep-002",
    status: "active",
    shiftPreference: "evening",
    createdAt: "2025-12-03",
  },
  {
    id: "stf-003",
    firstName: "Salma",
    lastName: "Jebali",
    email: "s.jebali@solidcare.tn",
    phone: "+216 71 900 203",
    role: "care_assistant",
    departmentId: "dep-004",
    status: "active",
    shiftPreference: "morning",
    createdAt: "2026-01-18",
  },
  {
    id: "stf-004",
    firstName: "Hedi",
    lastName: "Masmoudi",
    email: "h.masmoudi@solidcare.tn",
    phone: "+216 71 900 204",
    role: "anesthetist",
    departmentId: "dep-003",
    status: "active",
    shiftPreference: "night",
    createdAt: "2025-09-22",
  },
  {
    id: "stf-005",
    firstName: "Ines",
    lastName: "Bouzid",
    email: "i.bouzid@solidcare.tn",
    phone: "+216 71 900 205",
    role: "technician",
    departmentId: "dep-005",
    status: "on_leave",
    shiftPreference: "morning",
    createdAt: "2026-02-10",
  },
  {
    id: "stf-006",
    firstName: "Rania",
    lastName: "Chaabane",
    email: "r.chaabane@solidcare.tn",
    phone: "+216 71 900 206",
    role: "admin_staff",
    departmentId: "dep-004",
    status: "active",
    createdAt: "2025-08-01",
  },
  {
    id: "stf-007",
    firstName: "Omar",
    lastName: "Feki",
    email: "o.feki@solidcare.tn",
    phone: "+216 71 900 207",
    role: "nurse",
    departmentId: "dep-006",
    status: "inactive",
    shiftPreference: "evening",
    createdAt: "2024-06-15",
  },
  {
    id: "stf-008",
    firstName: "Nadia",
    lastName: "Karray",
    email: "n.karray@solidcare.tn",
    phone: "+216 71 900 208",
    role: "technician",
    departmentId: "dep-001",
    status: "active",
    shiftPreference: "night",
    createdAt: "2026-03-05",
  },
];
