import type { Doctor } from "./types";

export const doctorSeed: Doctor[] = [
  {
    id: "doc-001",
    firstName: "Leila",
    lastName: "Ben Amor",
    specialty: "General medicine",
    licenseNumber: "TN-GM-4021",
    phone: "+216 71 900 112",
    email: "l.benamor@solidcare.tn",
    consultationFee: 60,
    availableDays: ["Mon", "Tue", "Wed", "Thu", "Fri"],
    status: "available",
    room: "A-101",
    departmentId: "dep-004",
  },
  {
    id: "doc-002",
    firstName: "Sami",
    lastName: "Bouazizi",
    specialty: "Cardiology",
    licenseNumber: "TN-CA-1187",
    phone: "+216 71 900 118",
    email: "s.bouazizi@solidcare.tn",
    consultationFee: 120,
    availableDays: ["Mon", "Wed", "Fri"],
    status: "available",
    room: "B-204",
    departmentId: "dep-001",
  },
  {
    id: "doc-003",
    firstName: "Mariem",
    lastName: "Sassi",
    specialty: "Paediatrics",
    licenseNumber: "TN-PE-3390",
    phone: "+216 71 900 124",
    email: "m.sassi@solidcare.tn",
    consultationFee: 70,
    availableDays: ["Tue", "Thu", "Sat"],
    status: "available",
    room: "A-108",
    departmentId: "dep-002",
  },
  {
    id: "doc-004",
    firstName: "Nizar",
    lastName: "Haddad",
    specialty: "Orthopaedics",
    licenseNumber: "TN-OR-7712",
    phone: "+216 71 900 131",
    email: "n.haddad@solidcare.tn",
    consultationFee: 110,
    availableDays: ["Mon", "Thu"],
    status: "on_leave",
    room: "C-002",
    departmentId: "dep-003",
  },
  {
    id: "doc-005",
    firstName: "Dorra",
    lastName: "Mejri",
    specialty: "Dermatology",
    licenseNumber: "TN-DE-5504",
    phone: "+216 71 900 145",
    email: "d.mejri@solidcare.tn",
    consultationFee: 90,
    availableDays: ["Wed", "Fri", "Sat"],
    status: "available",
    room: "B-110",
    departmentId: "dep-005",
  },
  {
    id: "doc-006",
    firstName: "Anis",
    lastName: "Rekik",
    specialty: "Gynaecology",
    licenseNumber: "TN-GY-2298",
    phone: "+216 71 900 150",
    email: "a.rekik@solidcare.tn",
    consultationFee: 100,
    availableDays: ["Tue", "Wed", "Thu"],
    status: "available",
    room: "C-115",
    departmentId: "dep-006",
  },
];
