import type { Room } from "./types";

export const roomSeed: Room[] = [
  {
    id: "room-001",
    name: "Consultation Cardiologie A",
    code: "C-201",
    departmentId: "dep-001",
    floor: "2",
    capacity: 2,
    roomType: "consultation",
    status: "available",
    notes: "ECG, tensiomètre, oxymètre",
    createdAt: "2025-02-10",
  },
  {
    id: "room-002",
    name: "Consultation Cardiologie B",
    code: "C-202",
    departmentId: "dep-001",
    floor: "2",
    capacity: 2,
    roomType: "consultation",
    status: "occupied",
    notes: "Échographe cardiaque portable",
    createdAt: "2025-02-10",
  },
  {
    id: "room-003",
    name: "Consultation Pédiatrie 1",
    code: "P-101",
    departmentId: "dep-002",
    floor: "1",
    capacity: 3,
    roomType: "consultation",
    status: "available",
    notes: "Balance pédiatrique, otoscope",
    createdAt: "2025-02-12",
  },
  {
    id: "room-004",
    name: "Consultation Pédiatrie 2",
    code: "P-102",
    departmentId: "dep-002",
    floor: "1",
    capacity: 2,
    roomType: "care",
    status: "maintenance",
    notes: "Climatisation en réparation",
    createdAt: "2025-02-12",
  },
  {
    id: "room-005",
    name: "Box Urgences 1",
    code: "U-01",
    departmentId: "dep-004",
    floor: "RDC",
    capacity: 1,
    roomType: "care",
    status: "occupied",
    notes: "Monitor multiparamétrique, défibrillateur",
    createdAt: "2025-03-01",
  },
  {
    id: "room-006",
    name: "Box Urgences 2",
    code: "U-02",
    departmentId: "dep-004",
    floor: "RDC",
    capacity: 1,
    roomType: "care",
    status: "available",
    notes: "Chariot d'urgence, aspirateur",
    createdAt: "2025-03-01",
  },
  {
    id: "room-007",
    name: "Consultation Dermatologie",
    code: "D-110",
    departmentId: "dep-005",
    floor: "1",
    capacity: 2,
    roomType: "exam",
    status: "available",
    notes: "Lampe de Wood, dermatoscope",
    createdAt: "2025-03-08",
  },
  {
    id: "room-008",
    name: "Consultation Gynécologie",
    code: "G-205",
    departmentId: "dep-006",
    floor: "2",
    capacity: 2,
    roomType: "consultation",
    status: "reserved",
    notes: "Table gynécologique, colposcope",
    createdAt: "2025-03-20",
  },
  {
    id: "room-009",
    name: "Salle d'échographie",
    code: "I-S01",
    departmentId: "dep-007",
    floor: "Sous-sol",
    capacity: 1,
    roomType: "ultrasound",
    status: "occupied",
    notes: "Échographe GE Voluson",
    createdAt: "2025-04-05",
  },
  {
    id: "room-010",
    name: "Consultation Orthopédie",
    code: "O-301",
    departmentId: "dep-008",
    floor: "3",
    capacity: 2,
    roomType: "radiology",
    status: "maintenance",
    notes: "En attente de remise en service",
    createdAt: "2025-05-22",
  },
  {
    id: "or-001",
    name: "Bloc opératoire 1",
    code: "BO-1",
    departmentId: "dep-003",
    floor: "3",
    capacity: 1,
    roomType: "operating",
    status: "available",
    notes: "Table chirurgicale, scialytique LED, anesthésie",
    createdAt: "2025-02-01",
  },
  {
    id: "or-002",
    name: "Bloc opératoire 2",
    code: "BO-2",
    departmentId: "dep-003",
    floor: "3",
    capacity: 1,
    roomType: "operating",
    status: "in_surgery",
    notes: "Laparoscopie, électrocautère. Intervention en cours.",
    createdAt: "2025-02-01",
  },
  {
    id: "or-003",
    name: "Bloc orthopédique",
    code: "BO-ORTH",
    departmentId: "dep-008",
    floor: "3",
    capacity: 2,
    roomType: "operating",
    status: "sterilizing",
    notes: "Amplificateur de brillance. Cycle de stérilisation.",
    createdAt: "2025-05-25",
  },
  {
    id: "or-004",
    name: "Bloc gynécologique",
    code: "BO-GYN",
    departmentId: "dep-006",
    floor: "2",
    capacity: 1,
    roomType: "operating",
    status: "maintenance",
    notes: "Révision climatisation salle blanche",
    createdAt: "2025-03-22",
  },
  {
    id: "or-005",
    name: "Salle de césarienne",
    code: "BO-CES",
    departmentId: "dep-006",
    floor: "2",
    capacity: 1,
    roomType: "operating",
    status: "available",
    notes: "Incubateur néonatal adjacent, monitoring fœtal",
    createdAt: "2025-03-22",
  },
  {
    id: "or-006",
    name: "Bloc d'urgence",
    code: "BO-URG",
    departmentId: "dep-004",
    floor: "RDC",
    capacity: 1,
    roomType: "operating",
    status: "available",
    notes: "Accès rapide, défibrillateur, set traumatologie",
    createdAt: "2025-03-05",
  },
];
