import type { Department } from "./types";

/** Départements fictifs d'une clinique tunisienne — données de démo uniquement. */
export const departmentSeed: Department[] = [
  {
    id: "dep-001",
    name: "Cardiologie",
    code: "CARDIO",
    description: "Consultations et explorations cardiovasculaires.",
    headDoctorId: "doc-002",
    teamLeaderId: "doc-002",
    doctorIds: ["doc-002", "doc-001"],
    status: "active",
    floor: "2",
    phone: "+216 71 900 200",
    createdAt: "2025-01-10",
  },
  {
    id: "dep-002",
    name: "Pédiatrie",
    code: "PEDIA",
    description: "Suivi des nourrissons, enfants et adolescents.",
    headDoctorId: "doc-003",
    teamLeaderId: "doc-003",
    doctorIds: ["doc-003"],
    status: "active",
    floor: "1",
    phone: "+216 71 900 210",
    createdAt: "2025-01-12",
  },
  {
    id: "dep-003",
    name: "Chirurgie générale",
    code: "CHIR",
    description: "Chirurgies programmées et suivi post-opératoire.",
    headDoctorId: "doc-004",
    teamLeaderId: "doc-001",
    doctorIds: ["doc-004", "doc-001"],
    status: "active",
    floor: "3",
    phone: "+216 71 900 220",
    createdAt: "2025-02-01",
  },
  {
    id: "dep-004",
    name: "Urgences",
    code: "URG",
    description: "Accueil des urgences médicales et traumatiques 24h/24.",
    headDoctorId: "doc-001",
    teamLeaderId: "doc-005",
    doctorIds: ["doc-001", "doc-005", "doc-002"],
    status: "active",
    floor: "RDC",
    phone: "+216 71 900 230",
    createdAt: "2025-02-15",
  },
  {
    id: "dep-005",
    name: "Dermatologie",
    code: "DERMA",
    description: "Consultations cutanées et actes dermatologiques.",
    headDoctorId: "doc-005",
    teamLeaderId: "doc-005",
    doctorIds: ["doc-005"],
    status: "active",
    floor: "1",
    phone: "+216 71 900 240",
    createdAt: "2025-03-05",
  },
  {
    id: "dep-006",
    name: "Gynécologie-Obstétrique",
    code: "GYNO",
    description: "Suivi gynécologique et consultations obstétricales.",
    headDoctorId: "doc-006",
    teamLeaderId: "doc-006",
    doctorIds: ["doc-006"],
    status: "active",
    floor: "2",
    phone: "+216 71 900 250",
    createdAt: "2025-03-18",
  },
  {
    id: "dep-007",
    name: "Imagerie médicale",
    code: "IMAG",
    description: "Radiologie, échographie et explorations d'imagerie.",
    headDoctorId: "doc-001",
    teamLeaderId: "doc-002",
    doctorIds: ["doc-001", "doc-002"],
    status: "active",
    floor: "Sous-sol",
    phone: "+216 71 900 260",
    createdAt: "2025-04-02",
  },
  {
    id: "dep-008",
    name: "Orthopédie",
    code: "ORTHO",
    description: "Pathologies ostéo-articulaires et traumatologie.",
    headDoctorId: "doc-004",
    teamLeaderId: "doc-004",
    doctorIds: ["doc-004"],
    status: "inactive",
    floor: "3",
    phone: "+216 71 900 270",
    createdAt: "2025-05-20",
  },
];
