import type { AuditEvent } from "./types";

export const auditEventSeed: AuditEvent[] = [
  {
    id: "aud-001",
    actorName: "Sonia Khelifi",
    actorRole: "Administrateur",
    action: "update",
    entityType: "settings",
    entityId: "clinic",
    createdAt: "2026-09-10T11:20:00",
    detail: "Mise à jour des paramètres de la clinique",
  },
  {
    id: "aud-002",
    actorName: "Karim Jaziri",
    actorRole: "Médecin",
    action: "create",
    entityType: "consultation",
    entityId: "con-014",
    createdAt: "2026-09-10T10:45:00",
    detail: "Consultation finalisée pour PAT-003",
  },
  {
    id: "aud-003",
    actorName: "Mariem Cherif",
    actorRole: "Réceptionniste",
    action: "create",
    entityType: "appointment",
    entityId: "apt-018",
    createdAt: "2026-09-10T09:55:00",
    detail: "Nouveau rendez-vous confirmé — salle C-201",
  },
  {
    id: "aud-004",
    actorName: "Hatem Gharbi",
    actorRole: "Chef de département",
    action: "update",
    entityType: "operating_room",
    entityId: "or-004",
    createdAt: "2026-09-10T08:10:00",
    detail: "Bloc gynécologique passé en maintenance",
  },
  {
    id: "aud-005",
    actorName: "Leila Mansouri",
    actorRole: "Chef d'équipe",
    action: "update",
    entityType: "planning",
    entityId: "shf-003",
    createdAt: "2026-09-09T16:30:00",
    detail: "Vacation infirmière cardio réaffectée",
  },
  {
    id: "aud-006",
    actorName: "Sonia Khelifi",
    actorRole: "Administrateur",
    action: "create",
    entityType: "user",
    entityId: "usr-006",
    createdAt: "2026-09-09T14:05:00",
    detail: "Invitation utilisateur Nizar Bouzid",
  },
  {
    id: "aud-007",
    actorName: "Mariem Cherif",
    actorRole: "Réceptionniste",
    action: "update",
    entityType: "patient",
    entityId: "pat-001",
    createdAt: "2026-09-09T11:22:00",
    detail: "Coordonnées patient mises à jour",
  },
  {
    id: "aud-008",
    actorName: "Karim Jaziri",
    actorRole: "Médecin",
    action: "create",
    entityType: "prescription",
    entityId: "rx-009",
    createdAt: "2026-09-08T15:40:00",
    detail: "Ordonnance créée pour PAT-012",
  },
];
