import type { OperatingRoom } from "./types";

export const operatingRoomSeed: OperatingRoom[] = [
  {
    id: "or-001",
    name: "Bloc opératoire 1",
    code: "BO-1",
    departmentId: "dep-003",
    floor: "3",
    tables: 1,
    status: "available",
    equipmentSummary: "Table chirurgicale, scialytique LED, anesthésie",
    notes: "",
    createdAt: "2025-02-01",
  },
  {
    id: "or-002",
    name: "Bloc opératoire 2",
    code: "BO-2",
    departmentId: "dep-003",
    floor: "3",
    tables: 1,
    status: "in_surgery",
    equipmentSummary: "Laparoscopie, électrocautère",
    notes: "Intervention en cours",
    createdAt: "2025-02-01",
  },
  {
    id: "or-003",
    name: "Bloc orthopédique",
    code: "BO-ORTH",
    departmentId: "dep-008",
    floor: "3",
    tables: 2,
    status: "sterilizing",
    equipmentSummary: "Amplificateur de brillance, table orthopédique",
    notes: "Cycle de stérilisation",
    createdAt: "2025-05-25",
  },
  {
    id: "or-004",
    name: "Bloc gynécologique",
    code: "BO-GYN",
    departmentId: "dep-006",
    floor: "2",
    tables: 1,
    status: "maintenance",
    equipmentSummary: "Table gynéco-opératoire",
    notes: "Révision climatisation salle blanche",
    createdAt: "2025-03-22",
  },
  {
    id: "or-005",
    name: "Salle de césarienne",
    code: "BO-CES",
    departmentId: "dep-006",
    floor: "2",
    tables: 1,
    status: "available",
    equipmentSummary: "Incubateur néonatal adjacent, monitoring fœtal",
    notes: "",
    createdAt: "2025-03-22",
  },
  {
    id: "or-006",
    name: "Bloc d'urgence",
    code: "BO-URG",
    departmentId: "dep-004",
    floor: "RDC",
    tables: 1,
    status: "available",
    equipmentSummary: "Accès rapide, défibrillateur, set traumatologie",
    notes: "",
    createdAt: "2025-03-05",
  },
];
